apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  selector:
    matchLabels:
      app: book-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: book-k8s-mysql
    spec:
      containers:
      - name: book-k8s-mysql
        image: go-book:3.1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_NAME
            value: bookdb
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: root
---
apiVersion: v1
kind: Service
metadata:
  name: book-app-svc
spec:
  selector:
    app: book-k8s-mysql
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 31007
  type: NodePort
  # externalIPs:
  # - 192.168.0.10



  
